sudo: required
language: node_js
node_js:
  - "0.12"
install:
  - "npm install -g typescript"
script:
    - tsc -p csComp
    - npm install
    - cd test && karma start karma.conf.js
notifications:
  slack: webcs:AnvBbkHIi7v9aTiS2H4suMkr
