sudo: false
language: node_js
node_js:
  - "5.5.0"
cache:
  directories:
    - "travis-phantomjs"
before_install:
  - "phantomjs --version"
  - "mkdir travis-phantomjs && PHANTOM_EXISTS=false"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $PHANTOM_EXISTS = 'false' ]; then tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs; fi"
  - "export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
install:
  - "npm install -g npm@3.8.3"
  - "npm install -g typescript@1.8.9"
  - "npm install -g bower"
  - "npm install"
script:
    - gulp travis
    # - cd .. && cat coverage/*/lcov.info | test/coveralls.js
notifications:
  slack: webcs:AnvBbkHIi7v9aTiS2H4suMkr
env:
  matrix:
    secure: TxWwQB+JJ87CiHT95wBgRGrUA6f46D3adx3FSDEi+KWrc/K15uARaoVWbPyX2OcFt1+QZDcJ7oQIa4F5cOp4e6caN1+pp8+kk7Un1WDDe5fqTeYxUypYWIIcosXAZyM4gAJin1t8RyHFUVdMVyDhQm0ONDda+vfsxL8GdNY/ZcI=
